# Generated by Django 3.1 on 2020-09-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecetasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recetario',
            options={'verbose_name': 'recetario', 'verbose_name_plural': 'recetarios'},
        ),
    ]
