# Generated by Django 3.1 on 2020-09-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecetasApp', '0002_auto_20200904_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetario',
            name='imagen',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
